services:
  postgres:
    image: postgres:17
    container_name: nextcloud-postgres
    restart: unless-stopped
    shm_size: 256MB
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_INITDB_ARGS=--data-checksums
      - TZ
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB}", "-U", "${POSTGRES_USER}"]
      interval: 10s
      timeout: 3s

  valkey:
    image: valkey/valkey:9
    container_name: nextcloud-valkey
    restart: unless-stopped
    environment:
      - TZ
    healthcheck:
      test: ["CMD", "valkey-cli", "PING"]
      interval: 10s
      timeout: 3s

  imaginary:
    image: ghcr.io/nextcloud-releases/aio-imaginary:latest
    container_name: nextcloud-imaginary
    restart: unless-stopped
    init: true
    healthcheck:
      interval: 10s
      timeout: 3s

  app:
    image: ghcr.io/william920429/nextcloud:latest
    container_name: nextcloud-app
    restart: unless-stopped
    # Uncomment to enable dri device (VA-API)
    # devices:
    #   - /dev/dri:/dev/dri
    volumes:
      - html:/var/www/html
      - cache:/var/www/cache
      # - /somewhere/my/data/store:/var/www/html/data
    tmpfs:
      - /tmp:exec
    env_file: .env
    ports:
      - 21800:80
    environment:
      - REDIS_HOST=valkey
      - POSTGRES_HOST=postgres
      - NOTIFYPUSH_HOST=localhost
    depends_on:
      - postgres
      - valkey

volumes:
  html:
  cache:
  postgres:
