services:
  postgres:
    image: postgres:17
    container_name: nextcloud-postgres
    restart: unless-stopped
    shm_size: 256MB
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_INITDB_ARGS=--data-checksums
      - TZ
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB}", "-U", "${POSTGRES_USER}"]
      interval: 10s
      timeout: 3s

  valkey:
    image: valkey/valkey:9
    container_name: nextcloud-valkey
    restart: unless-stopped
    environment:
      - VALKEY_EXTRA_FLAGS=--save "" --appendonly no
      - TZ
    healthcheck:
      test: ["CMD", "valkey-cli", "PING"]
      interval: 10s
      timeout: 3s

  imaginary:
    image: ghcr.io/nextcloud-releases/aio-imaginary:latest
    container_name: nextcloud-imaginary
    restart: unless-stopped
    entrypoint: imaginary -p 9000 -return-size -max-allowed-resolution 222.2
    healthcheck:
      test: ["CMD", "nc", "-z", "127.0.0.1", "9000"]
      interval: 10s
      timeout: 3s

  app:
    image: ghcr.io/william920429/nextcloud:latest
    container_name: nextcloud-app
    restart: unless-stopped
    # Uncomment to enable dri device (VA-API)
    # devices:
    #   - /dev/dri:/dev/dri
    volumes:
      - html:/var/www/html
      - cache:/var/www/cache
      # - /somewhere/my/data/store:/var/www/html/data
    tmpfs:
      - /tmp:exec
    env_file: .env
    ports:
      - 21800:80
    healthcheck:
      test: ["CMD", "nc", "-z", "127.0.0.1", "80"]
      interval: 10s
      timeout: 3s
    depends_on:
      - postgres
      - valkey
  
  cron:
    image: ghcr.io/william920429/nextcloud:latest
    container_name: nextcloud-cron
    stop_signal: SIGTERM
    restart: unless-stopped
    command: supercronic -quiet /var/spool/cron/crontabs/www-data
    # Uncomment to enable dri device (VA-API)
    # devices:
    #   - /dev/dri:/dev/dri
    env_file: .env
    volumes_from:
      - app

  notifypush:
    image: ghcr.io/william920429/nextcloud:latest
    container_name: nextcloud-notifypush
    stop_signal: SIGTERM
    restart: unless-stopped
    command: |
      notify_push
        --port "7867"
        --database-url "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}/${POSTGRES_DB}"
        --database-prefix "oc_"
        --redis-url "redis://${REDIS_HOST}"
        --nextcloud-url "http://${NEXTCLOUD_HOST}"
    healthcheck:
      test: ["CMD", "nc", "-z", "127.0.0.1", "7867"]
      interval: 10s
      timeout: 3s
    env_file: .env
    volumes_from:
      - app

volumes:
  html:
  cache:
  postgres:
