services:
  postgres:
    image: postgres:17
    container_name: nextcloud-postgres
    restart: unless-stopped
    shm_size: 256MB
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_INITDB_ARGS="--data-checksums"
      - TZ
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB}", "-U", "${POSTGRES_USER}"]
      interval: 10s
      timeout: 3s

  redis:
    image: redis:latest
    container_name: nextcloud-redis
    restart: unless-stopped
    volumes:
      - redis:/data
    environment:
      - TZ
    healthcheck:
      test: ["CMD", "redis-cli", "PING"]
      interval: 10s
      timeout: 3s

  imaginary:
    image: ghcr.io/nextcloud-releases/aio-imaginary:latest
    container_name: nextcloud-imaginary
    restart: unless-stopped
    init: true

  app:
    image: ghcr.io/william920429/nextcloud:latest
    container_name: nextcloud-app
    restart: unless-stopped
    # Uncomment to enable dri device (VA-API)
    # devices:
    #   - /dev/dri:/dev/dri
    volumes:
      - html:/var/www/html
      - log:/var/www/log
      - cache:/var/www/cache
      # - /somewhere/my/data/store:/var/www/html/data
    tmpfs:
      - /tmp:exec
    env_file: .env
    ports:
      - 8080:80
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=postgres
    depends_on:
      - postgres
      - redis
volumes:
  html:
  log:
  cache:
  postgres:
  redis:
