services:
  postgres:
    image: postgres:17
    container_name: nextcloud-postgres
    restart: unless-stopped
    shm_size: 256MB
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_INITDB_ARGS="--data-checksums"
      - TZ
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD

  redis:
    image: redis:latest
    container_name: nextcloud-redis
    restart: unless-stopped
    volumes:
      - redis:/data
    environment:
      - TZ

  imaginary:
    image: ghcr.io/nextcloud-releases/aio-imaginary:latest
    container_name: nextcloud-imaginary
    restart: unless-stopped
    init: true
    healthcheck:
      test: ["NONE"]
    tmpfs:
      - /tmp

  app:
    image: ghcr.io/william920429/nextcloud:latest
    container_name: nextcloud-app
    restart: unless-stopped
    # Uncomment to enable dri device (VA-API)
    # devices:
    #   - /dev/dri:/dev/dri
    volumes:
      - html:/var/www/html
      - data:/var/www/data
      # - /somewhere/my/data/store:/var/www/data
    env_file: .env
    ports:
      - 8080:80
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=postgres
    depends_on:
      - postgres
      - redis
volumes:
  html:
  data:
  postgres:
  redis:
