name: Build image

on:
  push:
    branches:
      - master
  schedule:
    - cron: "18 18 * * 2,6"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.actor }}/nextcloud
  NEXTCLOUD_MAJOR: 31
  DLIB_VERSION: 20.0
  PDLIB_VERSION: 1.1.0
  PUSH_VERSION: 1.2.0

jobs:
  image-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Pull docker image
        run: docker pull nextcloud:${{ env.NEXTCLOUD_MAJOR }}-apache

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./image
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.NEXTCLOUD_MAJOR }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          platforms: linux/amd64
          build-args: |
            NEXTCLOUD_MAJOR=${{ env.NEXTCLOUD_MAJOR }}
            DLIB_VERSION=${{ env.DLIB_VERSION }}
            PDLIB_VERSION=${{ env.PDLIB_VERSION }}
            PUSH_VERSION=${{ env.PUSH_VERSION }}
